mian.exe : labirinth.c maze_rdy.c maze_rdy.h maze_path_fnd.c maze_path_fnd.h
    gcc -std=c99 -Wall -Werror -pedantic -ggdb labirinth.c maze_rdy.c maze_rdy.h maze_path_fnd.c maze_path_fnd.h -o main.exe
	
clean :
	$(RM) *.exe
